#server:
#  port: 8443
#  ssl:
#    enabled: true
#    keyAlias: test-ssl2
#    key-store: src/main/resources/test-ssl2.p12
#    key-store-type: PKCS12
#    key-password: 123456
#    key-store-password: 123456




